version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3535:3535"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
    networks:
      - dev_network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5174:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - dev_network

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dev_network

  

networks:
  dev_network:
    driver: bridge
